<?php


trait Elasticsearch_TraitQuery
{

    public function getAllOfLastMinute($condition = null, $time = 0)
    {
        $query = static::getQueryTemplate();
        if(empty($time)){
            $time = time();
        }
        $timeStart = date('Y-m-d H:i:s', $time - 90);
        $timeEnd = date('Y-m-d H:i:s', $time - 30);
        $timestamp = [
            "gte" => $timeStart,
            "lte" => $timeEnd,
        ];
        $timestamp = array_map(function ($item) {
            return date("Y-m-d\TH:i:s", strtotime($item));
        }, $timestamp);

        $query['query'] = [
            "bool" => [
                "must" => [
                    [
                        'range' => [
                            "@timestamp" => $timestamp,
                        ]
                    ]
                ]
            ]
        ];

        if ($condition) {
            $query['query']['bool']['must'][] = [
                "match" => $condition
            ];
        }

//        var_dump($query);exit();
        return parent::getAll($query); // TODO: Change the autogenerated stub
    }


}
